export const GET_TICKERS = 'GET_TICKERS';
export const GET_TICKERS_SUCCESS = 'GET_TICKERS_SUCCESS';
export const GET_TICKERS_FAILED = 'GET_TICKERS_FAILED';
export const TOGGLE_TREEVIEW_VISIBILITY = 'TOGGLE_TREEVIEW_VISIBILITY';
