export const GET_TICKERS = 'GET_TICKERS';
export const GET_TICKERS_SUCCESS = 'GET_TICKERS_SUCCESS';
export const GET_TICKERS_FAILED = 'GET_TICKERS_FAILED';
export const GET_HISTO_DAY = 'GET_HISTO_DAY';
export const GET_HISTO_DAY_SUCCESS = 'GET_HISTO_DAY_SUCCESS';
export const GET_HISTO_DAY_FAILED = 'GET_HISTO_DAY_FAILED';
export const TOGGLE_TREEMAP_VISIBILITY = 'TOGGLE_TREEMAP_VISIBILITY';
export const SELECT_TREEMAP = 'SELECT_TREEMAP_OPTION';
